export enum OrderStatus {
  CREATED = 'CREATED',
  ACCEPTED_BY_MERCHANT = 'ACCEPTED_BY_MERCHANT',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  PICKED_UP = 'PICKED_UP',
  ON_THE_WAY = 'ON_THE_WAY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}
