export enum TransactionType {
  TRANSFER = 'TRANSFER',
  TOPUP = 'TOPUP',
  WITHDRAW = 'WITHDRAW',
  QR_PAYMENT = 'QR_PAYMENT',
  NFC_PAYMENT = 'NFC_PAYMENT',
  TAXI_RIDE = 'TAXI_RIDE',
  FOOD_ORDER = 'FOOD_ORDER',
  REVERSAL = 'REVERSAL',
  SYSTEM_ADJUSTMENT = 'SYSTEM_ADJUSTMENT',
}
